apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-no-bs-config
data:
  xray.json: |
    {
      "log": {
        "loglevel": {{ .Values.logLevel | default "critical" | quote }}
      },
      "dns": {
        "servers": ["1.1.1.1", "localhost"],
        "queryStrategy": {{ .Values.dnsQueryStrategy | default "UseIPv4" | quote }}
      },
      "outbounds": [
        {
          "tag": "direct",
          "protocol": "freedom"
        }
      ],
      "inbounds": [
        {
          "port": {{ required "You must specify an inbound port" .Values.port }},
          "protocol": "vless",
          "settings": {
            "decryption": "none",
            "clients": [
            {{ range $index, $user := required "You must specify a list of user IDs" .Values.users -}}
              {{ if $index }}, {{ else }}  {{ end -}}
              { "id": {{ required "User needs an ID" $user.id | quote }},
                "flow": "xtls-rprx-vision" }
            {{ end -}}
            ]
          },
          "streamSettings": {
            "network": "raw",
            "security": "reality",
            "realitySettings": {
              {{ if .Values.debugReality }}"show": true,{{ end }}
              "dest": {{ required "REALITY needs a spoofing target to work" .Values.realityTarget | quote }},
              "serverNames": [
                {{ required  "REALITY server name needs to be specified explicitly as it could be different from the spoofing target's hostname" .Values.realityServerName | quote }}
              ],
              "privateKey": {{ required "You must specify a private key for REALITY" .Values.privateKey | quote }},
              "shortIds": ["", "12345678"]
            },
            "sockopt": {
              "acceptProxyProtocol": true,
              "tcpFastOpen": true
            }
          }
        }
      ]
    }
