apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-no-bs-config
data:
  server.json: |
    {
      "log": {
        "loglevel": {{ .Values.logLevel | default "critical" | quote }},
        "output": "none",
        "error": "none",
        "access": "none",
        "dnsLog": false,
        "logid": true,
        "header": true
      },
      "dns": {
        "servers": ["1.1.1.1", "localhost"],
        "queryStrategy": {{ .Values.dnsQueryStrategy | default "UseIPv4" | quote }}
      },
      "outbounds": [
        {
          "tag": "direct",
          "protocol": "freedom"
        },
        {
          "tag": "blackhole",
          "protocol": "blackhole"
        },
        {
          "tag": "dns",
          "protocol": "dns",
          "settings": { "port": 53 }
        }
      ],
      "inbounds": [
        {
          "port": {{ required "You must specify an inbound port" .Values.port }},
          "protocol": "vless",
          "settings": {
            "decryption": "none",
            "fallbacks": [],
            "clients": [
            {{ range $index, $user := required "You must specify a list of user IDs" .Values.users -}}
              {{ if $index }}, {{ else }}  {{ end -}}
              { "id": {{ required "User needs an ID" $user.id | quote }},
                "flow": "xtls-rprx-vision" }
            {{ end -}}
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "dest": {{ required "REALITY needs a spoofing target to work" .Values.realityTarget | quote }},
              "serverNames": [ {{ .Values.realityServerName | default .Values.realityTarget | quote }} ],
              "privateKey": {{ required "You must specify a private key for REALITY" .Values.privateKey | quote }},
              "shortIds": [""]
            },
            "sockopt": {
                "acceptProxyProtocol": true,
                "tcpFastOpen": true
            }
          },
          "sniffing": {
            {{ if .Values.enableSniffing -}}
            "enabled": true,
            "routeOnly": true,
            "destOverride": ["http", "tls", "quic"]
            {{- else -}}
            "enabled": false
            {{- end }}
          }
        }
      ],
      "routing": {
        "domainStrategy": "IPOnDemand",
        "domainMatcher": "hybrid",
        "rules": [
          {
            "type": "field",
            "outboundTag": "freedom",
            "ip": ["127.0.0.1"],
            "port": "443,80,53"
          },
          {
            "type": "field",
            "port": 53,
            "network": "tcp,udp",
            "outboundTag": "dns"
          },
          {
            "type": "field",
            "port": 443,
            "network": "udp",
            "outboundTag": "blackhole"
          },
          {
            "type": "field",
            "port": "0-65535",
            "outboundTag": "freedom"
          }
        ]
      }
    }
