{{ $defaultVersion := "25.9.11" }}
{{ $cfgDir := "/etc/xray" }}
{{ $cfgFile := "config.json" }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-no-bs-xray
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-no-bs-xray
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-no-bs-xray
      annotations:
        always-reroll: {{ randAlphaNum 5 | quote }}
    spec:
      terminationGracePeriodSeconds: 5
      tolerations: # see: <https://kubernetes.io/docs/concepts/workloads/controllers/daemonset>
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: no-bs-xray
          image: ghcr.io/xtls/xray-core:{{ .Values.XrayVersion | default $defaultVersion }}
          args: [-c, {{ print $cfgDir "/" $cfgFile | quote }}]
          ports:
            - containerPort: {{ .Values.port }}
              hostPort: {{ .Values.port }}
              protocol: TCP
            - containerPort: {{ .Values.port }}
              hostPort: {{ .Values.port }}
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: {{ $cfgDir | quote }}
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-no-bs-config
            items:
              - key: xray.json
                path: {{ $cfgFile | quote }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - { key: no-bs, operator: NotIn, values: [cap] }
